server:
  port: 8080

app:
  # Path to the existing SQLite DB used by the Node backend
  sqlite:
    path: ../backend/trade.db

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

